"""G1 (F26): an offline geo-resolver over bundled GeoNames TSV.

Read-only access to bundled `sorta/data/geo/{places,names}.tsv`
(the path is injected — see `GeoResolver.__init__`). No FS writes, DB, or network.
Sanitizing names for the filesystem is sorter's job, not this module's.

`places.tsv` format (no header, TSV): geonameid, lat, lon, fcode, cc,
admin1, admin2, name_en(asciiname), population — generated by
`scripts/build_geodata.py` from GeoNames cities1000.

`names.tsv` format (no header, TSV): geonameid, lang, name — localized names
(ru/en/ja) from alternateNamesV2.

Missing `places.tsv` is a LOUD error (F65): without it the resolver returns empty
places for every coordinate, and the whole pipeline silently loses geo ground truth.
The optional files (`admin1.tsv`/`countries.tsv`/`names.tsv`) only degrade the
result — they are reported with a one-off warning instead.
"""
from __future__ import annotations

import bisect
import csv
import logging
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.spatial import cKDTree

from .faults import Fault
from .i18n import Lang

_log = logging.getLogger(__name__)

# GeoNames feature codes we consider a "city" (seat of admin) —
# everything else in places.tsv (PPLX etc.) is considered a "district".
_CITY_FCODES = frozenset({"PPLC", "PPLA", "PPLA2", "PPLA3", "PPLA4"})

PLACES_FILE = "places.tsv"

# F65: package data — the only layout that survives `pip install`/`uv tool install`
# (the repository-root `data/` is not part of the wheel). _LEGACY_DATA_DIR is the old
# repo layout: a working tree checked out before the move still has the files there.
_DEFAULT_DATA_DIR = Path(__file__).resolve().parent / "data" / "geo"
_LEGACY_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "geo"

_MISSING_DATA_HINT = (
    "geo data not found: {path} is missing. The bundled GeoNames data must live "
    "inside the package (sorta/data/geo). Rebuild it with "
    "`python scripts/build_geodata.py` or reinstall sorta — without it every "
    "coordinate resolves to an empty place."
)


class GeoDataMissing(Fault, FileNotFoundError):
    """Bundled `places.tsv` is not where the resolver looked for it."""

    codes = ("geo_data_missing",)


def _default_data_dir() -> Path:
    """Package data dir, falling back to the old repo layout if it is absent.

    Order: package -> repo. If neither exists we still return the package path — it
    is the one the error message should point at.
    """
    if (_DEFAULT_DATA_DIR / PLACES_FILE).exists():
        return _DEFAULT_DATA_DIR
    if (_LEGACY_DATA_DIR / PLACES_FILE).exists():
        return _LEGACY_DATA_DIR
    return _DEFAULT_DATA_DIR


@dataclass(frozen=True)
class Resolution:
    """Coordinate-resolve result: codes/geonameid, without localized names."""

    country_cc: str | None
    city_id: int | None
    district_id: int | None


@dataclass(frozen=True)
class _Place:
    geonameid: int
    lat: float
    lon: float
    fcode: str
    cc: str
    admin1: str
    name_en: str
    # F201: the 9th column of places.tsv, kept because a prefix search has to RANK its
    # answer — «Моск» finds «Москва» and a dozen hamlets, and only the population tells
    # them apart. 0 means "the base does not say", not "empty".
    population: int = 0


# F201: a name is split into words on everything that is not a letter or a digit —
# spaces, hyphens, apostrophes, parentheses and the combining marks the bundled base
# carries.
_WORD_SPLIT_RE = re.compile(r"[^\w]+", re.UNICODE)


def _name_words(name: str) -> list[str]:
    """The words a name can be found by: «Нижний Новгород» -> «нижний», «новгород».

    Word starts, not substrings: a substring match would answer «Рим» with every
    «Дурим» in the base and drown the list, while a word inside a composite name is
    exactly what a person types («Новг» for «Нижний Новгород»). Casefolded, like the
    rest of the reverse indexes.
    """
    return [w for w in _WORD_SPLIT_RE.split(name.casefold()) if w]


def _starts_a_word(text: str, key: str) -> bool:
    """True if `key` begins `text` at its start or right after a separator.

    The same rule `_name_words` states, applied to a query that has grown past one
    word: typing does not stop at a space, so «Нижний Новг» has to keep finding
    «Нижний Новгород» and «Sankt-Pet» has to survive the hyphen the words were split
    on. Both arguments are expected casefolded.
    """
    pos = text.find(key)
    while pos != -1:
        if pos == 0 or _WORD_SPLIT_RE.match(text[pos - 1]):
            return True
        pos = text.find(key, pos + 1)
    return False


def _to_xyz(lat_deg: np.ndarray | float, lon_deg: np.ndarray | float) -> np.ndarray:
    """Geodetic coordinates (deg.) -> point(s) on the unit sphere (x,y,z).

    Gives a monotonic correspondence of the Euclidean nearest-neighbour to the
    great-circle distance — the same trick reverse_geocoder uses for cKDTree.
    """
    lat = np.radians(lat_deg)
    lon = np.radians(lon_deg)
    x = np.cos(lat) * np.cos(lon)
    y = np.cos(lat) * np.sin(lon)
    z = np.sin(lat)
    return np.stack([x, y, z], axis=-1)


class GeoResolver:
    """An offline Country/City/District resolver over bundled GeoNames.

    Data is read lazily on the first call to `resolve()`/`name()`; a missing
    `places.tsv` raises `GeoDataMissing` there (use `data_available()` to check
    beforehand without loading anything).
    """

    def __init__(self, data_dir: str | Path | None = None) -> None:
        self._data_dir = Path(data_dir) if data_dir is not None else _default_data_dir()
        self._loaded = False
        self._places: dict[int, _Place] = {}
        self._names: dict[int, dict[str, str]] = {}
        # admin1 regions and countries: (cc, admin1)/cc -> geonameid whose localized
        # ru/en/ja lives in names.tsv (G-#19: trip names by region/country).
        # _extra_en — the asciiname fallback for region/country geonameids that are
        # not in places.tsv (they are not part of cities1000).
        self._region_gid: dict[tuple[str, str], int] = {}
        self._country_gid: dict[str, int] = {}
        self._extra_en: dict[int, str] = {}
        self._all_ids: list[int] = []
        self._all_tree: cKDTree | None = None
        self._city_ids: list[int] = []
        self._city_tree: cKDTree | None = None
        # F46: reverse lookups (name -> cc/geonameid), lazily built and cached by
        # lang on first access (see _country_name_index/_city_name_index) —
        # casefold keys, without changing the _names/_places format.
        self._country_name_idx: dict[str, dict[str, str]] = {}
        self._city_name_idx: dict[str, dict[str, list[int]]] = {}
        # F202: the same reverse lookup for admin1 regions — name -> geonameids. A
        # region is a place a person names («Карелия», «Тоскана») and the picker has to
        # find it; 3 865 of them is small enough that a scan of the built index answers
        # a prefix without an index of its own (the reasoning of country_ccs_by_prefix).
        self._region_name_idx: dict[str, dict[str, list[int]]] = {}
        # geonameid -> (cc, admin1): the reverse of _region_gid, so an id that arrived
        # from outside can be checked for being a region at all.
        self._region_key_by_gid: dict[int, tuple[str, str]] = {}
        # F201: (word, geonameid) sorted by word — the prefix index behind the place
        # picker, lazily built per lang like the two above.
        self._city_prefix_idx: dict[str, list[tuple[str, int]]] = {}

    @property
    def data_dir(self) -> Path:
        """Where this resolver reads the bundled data from (for errors/diagnostics)."""
        return self._data_dir

    def data_available(self) -> bool:
        """True if `places.tsv` is in place — a cheap check that loads nothing."""
        return (self._data_dir / PLACES_FILE).exists()

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        self._load_places()
        self._load_admin1()
        self._load_countries()
        self._load_names()
        self._build_trees()
        # Marked as loaded only AFTER a successful load: a failed one must keep
        # raising on every call, not degrade into a silently empty resolver.
        self._loaded = True

    def _warn_optional_missing(self, path: Path) -> None:
        """One-off warning for an optional file: loading goes on, the result degrades."""
        _log.warning(
            "geo data: optional %s is missing (%s) — localized region/country names "
            "will be unavailable; rebuild with `python scripts/build_geodata.py`",
            path.name, path,
        )

    def _load_places(self) -> None:
        path = self._data_dir / PLACES_FILE
        if not path.exists():
            # F65: the main file — staying silent here turns every coordinate into an
            # empty place and fakes "exact_gps" all the way down to the DB.
            raise GeoDataMissing(_MISSING_DATA_HINT.format(path=path),
                                 "geo_data_missing", path=str(path))
        with path.open(encoding="utf-8", newline="") as f:
            for row in csv.reader(f, delimiter="\t"):
                if len(row) < 9:
                    continue
                gid_s, lat_s, lon_s, fcode, cc = row[0], row[1], row[2], row[3], row[4]
                admin1 = row[5]
                name_en = row[7]
                try:
                    gid = int(gid_s)
                    lat = float(lat_s)
                    lon = float(lon_s)
                except ValueError:
                    continue
                try:
                    population = int(row[8])
                except ValueError:
                    # A blank or broken population is not worth losing the place over:
                    # it only costs this one its rank in a prefix search.
                    population = 0
                self._places[gid] = _Place(
                    geonameid=gid, lat=lat, lon=lon, fcode=fcode, cc=cc,
                    admin1=admin1, name_en=name_en or str(gid), population=population,
                )

    def _load_admin1(self) -> None:
        """admin1.tsv (cc, admin1, geonameid, name_en) -> (cc, admin1) -> geonameid.

        The file is optional (older bundled data without it — region names are simply
        unavailable, the accessors return None). The localized region name is taken
        from names.tsv by geonameid; name_en goes into _extra_en as a fallback.
        """
        path = self._data_dir / "admin1.tsv"
        if not path.exists():
            self._warn_optional_missing(path)
            return
        with path.open(encoding="utf-8", newline="") as f:
            for row in csv.reader(f, delimiter="\t"):
                if len(row) < 4:
                    continue
                cc, admin1, gid_s, name_en = row[0], row[1], row[2], row[3]
                try:
                    gid = int(gid_s)
                except ValueError:
                    continue
                if not cc or not admin1:
                    continue
                self._region_gid[(cc, admin1)] = gid
                self._region_key_by_gid[gid] = (cc, admin1)
                if name_en:
                    self._extra_en[gid] = name_en

    def _load_countries(self) -> None:
        """countries.tsv (cc, geonameid, name_en) -> cc -> geonameid (trip-name
        fallback when the region is unknown). The file is optional."""
        path = self._data_dir / "countries.tsv"
        if not path.exists():
            self._warn_optional_missing(path)
            return
        with path.open(encoding="utf-8", newline="") as f:
            for row in csv.reader(f, delimiter="\t"):
                if len(row) < 3:
                    continue
                cc, gid_s, name_en = row[0], row[1], row[2]
                try:
                    gid = int(gid_s)
                except ValueError:
                    continue
                if not cc:
                    continue
                self._country_gid[cc] = gid
                if name_en:
                    self._extra_en[gid] = name_en

    def _load_names(self) -> None:
        path = self._data_dir / "names.tsv"
        if not path.exists():
            self._warn_optional_missing(path)
            return
        with path.open(encoding="utf-8", newline="") as f:
            for row in csv.reader(f, delimiter="\t"):
                if len(row) < 3:
                    continue
                gid_s, lang, name = row[0], row[1], row[2]
                if not name:
                    continue
                try:
                    gid = int(gid_s)
                except ValueError:
                    continue
                self._names.setdefault(gid, {})[lang.strip().lower()] = name

    def _build_trees(self) -> None:
        if not self._places:
            return
        self._all_ids = list(self._places.keys())
        self._all_tree = cKDTree(_to_xyz(
            np.array([self._places[i].lat for i in self._all_ids]),
            np.array([self._places[i].lon for i in self._all_ids]),
        ))

        self._city_ids = [i for i in self._all_ids if self._places[i].fcode in _CITY_FCODES]
        if self._city_ids:
            self._city_tree = cKDTree(_to_xyz(
                np.array([self._places[i].lat for i in self._city_ids]),
                np.array([self._places[i].lon for i in self._city_ids]),
            ))

    def resolve(self, lat: float, lon: float) -> Resolution:
        """Nearest city/place for the coordinates.

        Raises `GeoDataMissing` if `places.tsv` is absent; all None — only if the file
        is there but holds no usable rows.
        """
        self._ensure_loaded()
        if self._all_tree is None:
            return Resolution(country_cc=None, city_id=None, district_id=None)

        point = _to_xyz(lat, lon)
        _, nearest_idx = self._all_tree.query(point)
        nearest_id = self._all_ids[int(nearest_idx)]
        nearest_place = self._places[nearest_id]

        city_id: int | None = None
        if self._city_tree is not None:
            _, city_idx = self._city_tree.query(point)
            city_id = self._city_ids[int(city_idx)]

        district_id: int | None = nearest_id
        if city_id is not None and nearest_id == city_id:
            district_id = None

        return Resolution(country_cc=nearest_place.cc or None, city_id=city_id,
                           district_id=district_id)

    def name(self, geonameid: int, lang: Lang) -> str:
        """Localized place name: lang -> en -> asciiname -> geonameid.

        Never crashes and never returns an empty string.
        """
        self._ensure_loaded()
        lang_key = str(lang).strip().lower()
        names = self._names.get(geonameid)
        if names:
            if lang_key in names:
                return names[lang_key]
            if "en" in names:
                return names["en"]
        place = self._places.get(geonameid)
        if place is not None and place.name_en:
            return place.name_en
        extra = self._extra_en.get(geonameid)
        if extra:
            return extra
        return str(geonameid)

    def has_localized_name(self, geonameid: int, lang: Lang) -> bool:
        """True if geonameid has a name SPECIFICALLY in `lang` in names.tsv.

        Unlike `name()`, does NOT fall back to en/asciiname — needed to tell
        "has a localized name" from "name() returned a transliteration via the
        fallback chain" (F49). An unknown geonameid or an empty resolver
        (no bundled data) -> False.
        """
        self._ensure_loaded()
        lang_key = str(lang).strip().lower()
        names = self._names.get(geonameid)
        return names is not None and lang_key in names

    def coords_of(self, geonameid: int) -> tuple[float, float] | None:
        """(lat, lon) of the city/place by geonameid; None — if the place is not in the data.

        For the geo-proximity of trip merging (G-#19): the distance between the
        cities of adjacent sessions.
        """
        self._ensure_loaded()
        place = self._places.get(geonameid)
        return (place.lat, place.lon) if place is not None else None

    def country_of(self, geonameid: int) -> str | None:
        """ISO cc of a city/place by geonameid; None — not in the data or no cc.

        `region_key_of` cannot answer this: it needs admin1 as well and returns nothing
        for a place whose region is blank, while the COUNTRY of such a place is known
        perfectly well — and the country is what a layout starts from (F85c: a city
        picked by hand still has to be filed under its country).
        """
        self._ensure_loaded()
        place = self._places.get(geonameid)
        return place.cc if place is not None and place.cc else None

    def population_of(self, geonameid: int) -> int:
        """Population of a city/place by geonameid; 0 — unknown or not in the data.

        Only a RANKING signal (F201: which of the places a typed prefix found is the
        one meant), never a fact the layout depends on.
        """
        self._ensure_loaded()
        place = self._places.get(geonameid)
        return place.population if place is not None else 0

    def region_key_of(self, geonameid: int) -> tuple[str, str] | None:
        """(cc, admin1) of the city — the region key for grouping/trip name.

        None — if the place is missing or has no cc/admin1 (then events fall back to
        country/city). Robust to empty admin1 in the bundled data.
        """
        self._ensure_loaded()
        place = self._places.get(geonameid)
        if place is None or not place.cc or not place.admin1:
            return None
        return (place.cc, place.admin1)

    def region_name(self, cc: str, admin1: str, lang: Lang) -> str | None:
        """Localized name of the admin1 region ((cc, admin1) -> «Бали»/«Bali»/«バリ島»).

        None — if the region is not in admin1.tsv (no targeted data). Never returns a
        bare geonameid — better None so the caller can fall back itself.
        """
        self._ensure_loaded()
        gid = self._region_gid.get((cc, admin1))
        if gid is None:
            return None
        nm = self.name(gid, lang)
        return nm if nm != str(gid) else None

    def country_name(self, cc: str, lang: Lang) -> str | None:
        """Localized country name by cc; None — if the country is not in countries.tsv."""
        self._ensure_loaded()
        gid = self._country_gid.get(cc)
        if gid is None:
            return None
        nm = self.name(gid, lang)
        return nm if nm != str(gid) else None

    # --- F46: reverse lookups (for a localized --where) ------------------------

    def _country_name_index(self, lang: Lang) -> dict[str, str]:
        """casefold(country name in lang, with an en fallback like in name()) -> cc.

        Built once per lang and cached. Countries have no ambiguity — the last entry
        in countries.tsv for a repeated name simply overwrites the previous one (in
        practice country names are unique).
        """
        self._ensure_loaded()
        lang_key = str(lang).strip().lower()
        idx = self._country_name_idx.get(lang_key)
        if idx is None:
            idx = {}
            for cc, gid in self._country_gid.items():
                nm = self.name(gid, lang)
                if nm and nm != str(gid):
                    idx[nm.casefold()] = cc
            self._country_name_idx[lang_key] = idx
        return idx

    def country_cc_by_name(self, name: str, lang: Lang) -> str | None:
        """A localized (or en) country name in lang -> ISO cc; None — not found."""
        return self._country_name_index(lang).get(name.strip().casefold())

    def _city_name_index(self, lang: Lang) -> dict[str, list[int]]:
        """casefold(city name in lang, with an en/asciiname fallback like in name()) ->
        a list of geonameid (same-named cities give several entries).

        Only "cities" (fcode from _CITY_FCODES, like city_id in resolve()) — the same
        geonameids that go into places.city_geonameid; districts (PPLX) are not
        included. Built once per lang and cached.
        """
        self._ensure_loaded()
        lang_key = str(lang).strip().lower()
        idx = self._city_name_idx.get(lang_key)
        if idx is None:
            idx = {}
            for gid in self._city_ids:
                nm = self.name(gid, lang)
                if nm:
                    idx.setdefault(nm.casefold(), []).append(gid)
            self._city_name_idx[lang_key] = idx
        return idx

    def city_ids_by_name(self, name: str, lang: Lang) -> list[int]:
        """A localized (or en/asciiname) city name in lang -> geonameids.

        Empty list — the name was not found. Several elements — same-named cities
        (different countries/regions).
        """
        return list(self._city_name_index(lang).get(name.strip().casefold(), []))

    # --- F202: the same lookups for admin1 REGIONS ------------------------------------
    # The base has always known regions — every city label reads «Петрозаводск
    # (Карельская республика, Россия)» — and nothing could be FOUND by one. People think
    # in regions where the collection has no city: «Карелия», «Тоскана», «Крым» are the
    # honest answer for frames whose owner remembers the trip and not the settlement.
    # A region carries its own geonameid (admin1.tsv), so it localizes through names.tsv
    # exactly as a city does, in the same three languages.

    def _region_name_index(self, lang: Lang) -> dict[str, list[int]]:
        """casefold(region name in lang, en fallback like in name()) -> geonameids.

        A list, not one id: region names repeat across countries — «Northern» names a
        region in a dozen of them — and picking between them is the user's business.
        Built once per lang and cached, like the city and country indexes above.

        The short administrative name of admin1.tsv is indexed BESIDE the localized one,
        because the base spells one region two ways and a person types either: 552548 is
        «Republic of Karelia» in names.tsv and plainly «Karelia» in admin1.tsv. Only the
        localized name is ever SHOWN (see `region_name`) — this is about what can be
        found, not about what a label reads.
        """
        self._ensure_loaded()
        lang_key = str(lang).strip().lower()
        idx = self._region_name_idx.get(lang_key)
        if idx is None:
            idx = {}
            for gid in self._region_gid.values():
                for nm in (self.name(gid, lang), self._extra_en.get(gid, "")):
                    if not nm or nm == str(gid):
                        continue
                    bucket = idx.setdefault(nm.casefold(), [])
                    if gid not in bucket:
                        bucket.append(gid)
            self._region_name_idx[lang_key] = idx
        return idx

    def region_ids_by_name(self, name: str, lang: Lang) -> list[int]:
        """A localized (or en) region name in lang -> geonameids; empty — not found."""
        return list(self._region_name_index(lang).get(name.strip().casefold(), []))

    def region_ids_by_prefix(self, prefix: str, lang: Lang) -> list[int]:
        """geonameids of regions whose name in `lang` has `prefix` at a word start.

        Scanned linearly for the reason `country_ccs_by_prefix` gives: 3 865 regions is
        a fortieth of the city index, and an index over them would cost more to build
        than every scan it saves. Order carries no meaning — the caller ranks.
        """
        key = prefix.strip().casefold()
        if not key:
            return []
        out: list[int] = []
        seen: set[int] = set()
        for name, gids in self._region_name_index(lang).items():
            if not _starts_a_word(name, key):
                continue
            for gid in gids:
                if gid not in seen:
                    seen.add(gid)
                    out.append(gid)
        return out

    def region_key_by_id(self, geonameid: int) -> tuple[str, str] | None:
        """(cc, admin1) of a REGION geonameid; None — not a region of admin1.tsv.

        The reverse of the key `region_name` takes, and the check an id that came from
        outside has to pass: `name()` answers anything at all (it ends its chain with the
        number itself), so it cannot tell a region from a typo.
        """
        self._ensure_loaded()
        return self._region_key_by_gid.get(geonameid)

    # --- F201: prefix lookups (for a picker that answers while the name is typed) ---
    # The full-name lookups above are right for `--where city=`, where the name is typed
    # whole, and wrong for a combobox: until the last letter is there the answer is
    # empty, and on the way it can hit a different city by accident. Measured on the
    # bundled base (63 034 cities, ~59 000 index keys per language): a linear pass over
    # the keys of all three languages costs 10–36 ms per keystroke, so the words are
    # indexed once instead (~280 ms per language, on the first search of the process)
    # and looked up with `bisect` — no new dependency, a sorted list is enough. The
    # whole `/api/places/search` answer then measures 0.2–2.5 ms for a six-letter query
    # and 0.3–10 ms for a three-letter one (the tail is the ranking of what a broad
    # prefix like "San" matches, not the lookup); the client debounces at 250 ms.

    def _city_prefix_index(self, lang: Lang) -> list[tuple[str, int]]:
        """(word, geonameid) pairs for every word of every city name in `lang`, sorted.

        One entry per word, so a composite name appears under each of its words; a
        same-named city pair appears under the same word twice. Built once per lang and
        cached, on the same index (and the same "city" feature codes) `city_ids_by_name`
        answers from.
        """
        lang_key = str(lang).strip().lower()
        pairs = self._city_prefix_idx.get(lang_key)
        if pairs is None:
            pairs = [(word, gid)
                     for name, gids in self._city_name_index(lang).items()
                     for word in _name_words(name)
                     for gid in gids]
            pairs.sort()
            self._city_prefix_idx[lang_key] = pairs
        return pairs

    def city_ids_by_prefix(self, prefix: str, lang: Lang) -> list[int]:
        """geonameids of cities whose name in `lang` has `prefix` at a word start.

        Case and surrounding whitespace are irrelevant, as in `city_ids_by_name`. An
        empty prefix is not a query and gives an empty list — "everything in the base"
        is never a useful answer here. The order (alphabetical by the matched word)
        carries no meaning: ranking the answer is the caller's business, because only
        the caller knows what the user typed it into.

        A query that spans a separator («Нижний Новг») cannot be found in an index of
        single words, so it is answered in two steps: the index narrows the base down
        by the FIRST word, and the whole query is then checked against those names.
        """
        key = prefix.strip().casefold()
        words = _name_words(key)
        if not key or not words:
            return []
        pairs = self._city_prefix_index(lang)
        found: list[int] = []
        seen: set[int] = set()
        for word, gid in pairs[bisect.bisect_left(pairs, (words[0], 0)):]:
            if not word.startswith(words[0]):
                break
            if gid not in seen:
                seen.add(gid)
                found.append(gid)
        if key == words[0]:
            return found
        return [gid for gid in found if _starts_a_word(self.name(gid, lang).casefold(),
                                                       key)]

    def country_ccs_by_prefix(self, prefix: str, lang: Lang) -> list[str]:
        """ISO ccs of countries whose name in `lang` has `prefix` at a word start.

        Scanned linearly on purpose: there are some 250 country names per language, and
        an index over them would cost more to build than every scan it saves.
        """
        key = prefix.strip().casefold()
        if not key:
            return []
        out: list[str] = []
        seen: set[str] = set()
        for name, cc in self._country_name_index(lang).items():
            if cc not in seen and _starts_a_word(name, key):
                seen.add(cc)
                out.append(cc)
        return out
